# Generated by Django 5.0.6 on 2024-07-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_futbol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservar_evento',
            name='cantidad_horas',
            field=models.IntegerField(),
        ),
    ]
