# Generated by Django 5.0.6 on 2024-07-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_futbol_app', '0002_alter_reservar_evento_cantidad_horas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buscar_rival',
            options={'ordering': ['dia_reserva', 'hora_reserva'], 'verbose_name': 'Buscando rival', 'verbose_name_plural': 'Buscandores de rival'},
        ),
        migrations.AlterModelOptions(
            name='reservar_cancha',
            options={'ordering': ['dia_reserva', 'hora_reserva'], 'verbose_name': 'Reserva de cancha', 'verbose_name_plural': 'Reservas de cancha'},
        ),
        migrations.AlterModelOptions(
            name='reservar_evento',
            options={'ordering': ['dia_reserva', 'hora_reserva'], 'verbose_name': 'Reserva de evento', 'verbose_name_plural': 'Reservas de evento'},
        ),
    ]
