# Generated by Django 5.0.6 on 2024-07-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_futbol_app', '0003_alter_buscar_rival_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscar_rival',
            name='dia_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='buscar_rival',
            name='hora_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservar_cancha',
            name='dia_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservar_cancha',
            name='hora_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservar_evento',
            name='dia_reserva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservar_evento',
            name='hora_reserva',
            field=models.CharField(max_length=20),
        ),
    ]
