# Generated by Django 5.0.6 on 2024-07-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_futbol_app', '0005_vendercomprar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendercomprar',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendercomprar',
            name='talle',
            field=models.CharField(max_length=10),
        ),
    ]
